### PR TITLE
Correct linter errors and add clarity in README.md

### LINKED ISSUE #23: Edit screenshot to use SSH url
@gaand Not sure if you wanted this filed, but I remember you mentioned it this morning.

https://camo.githubusercontent.com/af653200d6d39d06d3f5debbdf829b184cd3e2c5/68747470733a2f2f68656c702e6769746875622e636f6d2f6173736574732f696d616765732f68656c702f7265706f7369746f72792f72656d6f7465732d75726c2e706e67

See https://github.com/ga-wdi-boston/fundamentals-diagnostic/commit/577dd049c417ba27ece0b8456ad4bc1be852ebeb#diff-04c6e90faac2675aa89e2176d2eec7d8R47

### PR DESCRIPTION
**Pull request by berziiii**
Provided more clarity in the README.md along with fixed linter errors on both diagnostic.md and README.md.

Close #23

### CODE REVIEW

**Comment by berziiii** [comment]
@J-Weeks let me know when you push the solution branch changes. 

@jrhorn424 can you review the pull request and merge if everything looks good? Thanks.

**Comment by gaand** [comment]
@berziiii: Please define "Bp prep", the title for this pull request.  Thanks.

**Comment by berziiii** [comment]
@gaand is this title better suited for the merge?

**Comment by gaand** [comment]
@berziiii Yes.  Thanks.

**Comment by berziiii** [comment]
@jrhorn424, can I get your eyes on this prior to merge? Thanks.

**Pull request merged**
